import type { NextPage } from "next";
import Head from "next/head";
import { useContext } from "react";
import Playlist from "../components/Playlist";
import { PlaylistContext } from "../context/playlistCtx";

const Home: NextPage = () => {
  const { playerState } = useContext(PlaylistContext);
  const { playlist } = playerState;
  return (
    <>
      <Head>
        <title>NFT Playlist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mb-32">
        {playlist.map((musicNft, index) => (
          <Playlist key={musicNft.id} nft={musicNft} index={index} />
        ))}
      </div>
    </>
  );
};

export default Home;
